using System;
using System.Collections.Generic;

namespace J3QQ4
{
    public class Emoji
    {
        public const string Bust_In_Silhouette = "👤";
        public const string Boy = "👦";
        public const string Girl = "👧";
        public const string Man = "👨";
        public const string Woman = "👩";
        public const string Family = "👪";
        public const string Couple = "👫";
        public const string Cop = "👮";
        public const string Dancers = "👯";
        public const string Bride_With_Veil = "👰";
        public const string Person_With_Blond_Hair = "👱";
        public const string Man_With_Gua_Pi_Mao = "👲";
        public const string Man_With_Turban = "👳";
        public const string Older_Man = "👴";
        public const string Older_Woman = "👵";
        public const string Baby = "👶";
        public const string Construction_Worker = "👷";
        public const string Princess = "👸";
        public const string Japanese_Ogre = "👹";
        public const string Japanese_Goblin = "👺";
        public const string Ghost = "👻";
        public const string Angel = "👼";
        public const string Alien = "👽";
        public const string Space_Invader = "👾";
        public const string Robot_Face = "🤖";
        public const string Imp = "👿";
        public const string Skull = "💀";
        public const string Grin = "😁";
        public const string Joy = "😂";
        public const string Smiley = "😃";
        public const string Smile = "😄";
        public const string Sweat_Smile = "😅";
        public const string Laughing = "😆";
        public const string Wink = "😉";
        public const string Blush = "😊";
        public const string Yum = "😋";
        public const string Relieved = "😌";
        public const string Heart_Eyes = "😍";
        public const string Smirk = "😏";
        public const string Unamused = "😒";
        public const string Sweat = "😓";
        public const string Pensive = "😔";
        public const string Confounded = "😖";
        public const string Kissing_Heart = "😘";
        public const string Kissing_Closed_Eyes = "😚";
        public const string Stuck_Out_Tongue_Winking_Eye = "😜";
        public const string Stuck_Out_Tongue_Closed_Eyes = "😝";
        public const string Disappointed = "😞";
        public const string Angry = "😠";
        public const string Rage = "😡";
        public const string Cry = "😢";
        public const string Persevere = "😣";
        public const string Triumph = "😤";
        public const string Disappointed_Relieved = "😥";
        public const string Fearful = "😨";
        public const string Weary = "😩";
        public const string Sleepy = "😪";
        public const string Tired_Face = "😫";
        public const string Sob = "😭";
        public const string Cold_Sweat = "😰";
        public const string Scream = "😱";
        public const string Astonished = "😲";
        public const string Flushed = "😳";
        public const string Dizzy_Face = "😵";
        public const string Mask = "😷";
        public const string Smile_Cat = "😸";
        public const string Joy_Cat = "😹";
        public const string Smiley_Cat = "😺";
        public const string Heart_Eyes_Cat = "😻";
        public const string Smirk_Cat = "😼";
        public const string Kissing_Cat = "😽";
        public const string Pouting_Cat = "😾";
        public const string Crying_Cat_Face = "😿";
        public const string Scream_Cat = "🙀";
        public const string No_Good = "🙅";
        public const string Ok_Woman = "🙆";
        public const string Bow = "🙇";
        public const string See_No_Evil = "🙈";
        public const string Hear_No_Evil = "🙉";
        public const string Speak_No_Evil = "🙊";
        public const string Raising_Hand = "🙋";
        public const string Raised_Hands = "🙌";
        public const string Person_Frowning = "🙍";
        public const string Person_With_Pouting_Face = "🙎";
        public const string Pray = "🙏";
    }
}